version: '3.7'
services:
  db:
    image: 'mysql:8.0'
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "laravel"
      MYSQL_PASSWORD: "laravel"
      MYSQL_DATABASE: "db"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80

  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: it_website
    ports:
      - 8000:80
      - 80:80
      - 443:443
    volumes:
      - ./:/var/www/html
